# Generated by Django 2.1.5 on 2019-02-26 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=100)),
                ('article', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('article_img', models.ImageField(blank=True, default='default.gpg', null=True, upload_to='article_pics')),
                ('thumbs_up', models.IntegerField(null=True)),
                ('thumbs_down', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profession', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='Select', max_length=10)),
                ('profile_img', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics')),
                ('website', models.CharField(max_length=50, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_BLOG.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ManyToManyField(to='MY_BLOG.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
