# Generated by Django 2.1.5 on 2019-02-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MY_BLOG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='article_img',
            field=models.ImageField(blank=True, default='default.gpg', null=True, upload_to='article_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ManyToManyField(to='MY_BLOG.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MY_BLOG.Profile'),
        ),
    ]
