# Generated by Django 2.1.5 on 2019-02-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MY_BLOG', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
