# Generated by Django 2.1.5 on 2019-03-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_BLOG', '0003_auto_20190303_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
