# Generated by Django 2.2 on 2019-04-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MY_BLOG', '0004_auto_20190303_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.TextField(default='Missing article!'),
        ),
    ]
